services:
  mysql:
    image: mysql:8.4
    container_name: cinema_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - cinema_network

  redis:
    image: redis:7.2-alpine
    container_name: cinema_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cinema_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cinema_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    # ports:
    #   - "4000:4000"
    depends_on:
      - mysql
      - redis
    networks:
      - cinema_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cinema_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - cinema_network

  nginx:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    container_name: cinema_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend
      - frontend
    networks:
      - cinema_network

networks:
  cinema_network:
    driver: bridge